import os
import shutil
import sys
from block import Block
from memory import Memory
from utility import Utility
import time


number_of_records, block_size, memory_size = input().split()

number_of_records, block_size, memory_size = [int(number_of_records), int(block_size), int(memory_size)]

if memory_size < 3:
    sys.exit("Incorrect input. Memory size > 2 required.")

Utility.generate_data(number_of_records)

path = os.getcwd()
data_dir_path = path+"/dataset"
data_filename = "/data.txt"
unsorted_data_block_dir_path = path+"/data_block"
run_dir_path = path+"/sorted_run"
initial_run_dir_path = run_dir_path+"/initial_run"
intermediate_run_dir_path = run_dir_path+"/intermediate_run"

# remove data generated by previously compiled code
shutil.rmtree(unsorted_data_block_dir_path, ignore_errors=True)
shutil.rmtree(run_dir_path, ignore_errors=True)

# external sorting algorithm starts here
start_time = time.time()

Utility.create_directories(unsorted_data_block_dir_path)

records = open(data_dir_path+data_filename).readlines()
# break dataset in small blocks/files based upon Block size
block_name = Utility.create_disk_blocks(block_size, records, unsorted_data_block_dir_path, "US_")
Utility.reinitialize_block_number()

counter = 0
memory = None
Utility.create_directories(initial_run_dir_path)
# block pointers represent the R_pointers.txt file which contains the Block_id of first block of every sorted run
blocks_pointers = open(initial_run_dir_path+"/R_pointers.txt","w")

while block_name != 'NULL':
    if counter % memory_size == 0:
        memory = Memory(block_size, memory_size)
    unsorted_data_block = open(unsorted_data_block_dir_path+"/"+block_name+".txt").readlines()
    block = Block(unsorted_data_block[:-1], unsorted_data_block[-1], block_size)
    memory.add_block(block)
    if memory.size() == memory_size:
        Utility.create_blocks_starting_pointers(blocks_pointers)
        memory.create_initial_runs(initial_run_dir_path, block_size)
    block_name = unsorted_data_block[-1]
    counter += 1

# if #blocks in memory < memory_size
if memory.size() > 0:
    Utility.create_blocks_starting_pointers(blocks_pointers)
    memory.create_initial_runs(initial_run_dir_path, block_size)

Utility.reinitialize_block_number()
blocks_pointers.close()

total_runs = Utility.get_runs_count(initial_run_dir_path+"/R_pointers.txt")
counter = 1
intermediate_run_parent_dir_path = intermediate_run_dir_path

if total_runs <= 1:
    Utility.generate_final_sorted_data(run_dir_path, initial_run_dir_path)
else:
    while total_runs > 1:
        memory = Memory(block_size, memory_size)
        # print("total runs: ", total_runs)
        new_intermediate_run_dir_path = memory.merge_runs(initial_run_dir_path, intermediate_run_dir_path, counter)
        initial_run_dir_path = intermediate_run_dir_path+"_"+str(counter)
        intermediate_run_dir_path = intermediate_run_parent_dir_path
        total_runs = Utility.get_runs_count(intermediate_run_dir_path+"_"+str(counter)+"/R_pointers.txt")
        counter += 1
    Utility.generate_final_sorted_data(run_dir_path, intermediate_run_dir_path+"_"+str(counter-1))

end_time = time.time()
# external sorting algorithm ends here

print("total time taken in secs: ",end_time-start_time,)
