import os
import random
import string

# block number is used to number the file while creating based on occurence
block_number = 1

class Utility:

    @staticmethod
    def reinitialize_block_number():
        global block_number
        block_number = 1

    @staticmethod
    def create_directories(dir_path):
        try:
        # create a new directory
            os.makedirs(dir_path)
        except OSError:
        # directory is already present
            pass
    
    @staticmethod
    def create_disk_blocks(block_size: int, data: list, data_block_dir_path: str, file_prefix: str) -> str:
        # create disk blocks based on block size
        global block_number
        data_block = open(data_block_dir_path+"/"+file_prefix+str(block_number)+".txt","w")
        initial_block_name = file_prefix+str(block_number)

        for i in range(0,len(data)):
            data_block.write(str(data[i]).strip('\n'))
            data_block.write('\n')
            if i == len(data)-1:
                block_number += 1
                data_block.write("NULL")
                data_block.close()
            elif (i+1) % block_size == 0:
                block_number += 1
                data_block.write(file_prefix+str(block_number))
                data_block.close()
                data_block = open(data_block_dir_path+"/"+file_prefix+str(block_number)+".txt","w")
        
        return initial_block_name

    @staticmethod
    def create_single_disk_block(block_size: int, data: list, data_block_dir_path: str, file_prefix: str, is_last_block: bool) -> str:
        # create disk block generated by the memory output block
        global block_number
        data_block = open(data_block_dir_path+"/"+file_prefix+str(block_number)+".txt","w")
        initial_block_name = file_prefix+str(block_number)

        for i in range(0,len(data)):
            data_block.write(str(data[i]).strip('\n'))
            data_block.write('\n')
            if i == len(data)-1:
                block_number += 1
                if is_last_block:
                    data_block.write("NULL")
                else:
                    data_block.write(file_prefix+str(block_number))
                data_block.close()
        
        return initial_block_name

    @staticmethod
    def create_blocks_starting_pointers(blocks_pointers):
        blocks_pointers.write('B_'+str(block_number)+"\n")

    @staticmethod
    def get_runs_count(file_path:str) -> int:
        """
        function return number of runs present
        """
        file = open(file_path, 'r')
        runs = file.readlines()
        file.close()
        return len(runs)

    @staticmethod
    def convert_tuple_string_list_to_string_list(input_list: list) -> list:
        return [str(eval(record)[0])+","+str(eval(record)[1])+","+eval(record)[2]+","+str(eval(record)[3])+"\n" for record in input_list]

    @staticmethod
    def generate_final_sorted_data(output_path:str, data_files_path:str):
        run_block_pointer = open(data_files_path+"/R_pointers.txt", 'r')
        run_initial_block = run_block_pointer.readlines()[0].strip()
        current_file = open(data_files_path+"/"+str(run_initial_block)+".txt").readlines()
        current_file_data = Utility.convert_tuple_string_list_to_string_list(current_file[:-1])
        next_file_block = current_file[-1]

        output_sorted_data = open(output_path+"/sorted_data.txt","w")
        output_sorted_data.writelines(current_file_data)

        while next_file_block != 'NULL':
            current_file = open(data_files_path+"/"+str(next_file_block)+".txt").readlines()
            current_file_data = Utility.convert_tuple_string_list_to_string_list(current_file[:-1])
            next_file_block = current_file[-1]
            output_sorted_data.writelines(current_file_data)

        output_sorted_data.close()

    @staticmethod
    def generate_data(number_of_records: int):
        path = os.getcwd()
        dir_path = path+"/dataset"
        filename = "/data.txt"
        char_array = list(string.ascii_uppercase)


        Utility.create_directories(dir_path)

        file = open(dir_path+filename,"w")


        for i in range(0,number_of_records):
            record = ''
            transaction_id = i+1
            transaction_sale_amount = random.randint(1,60000)
            customer_name = ''.join([str(i) for i in random.sample(char_array,3)])
            category_of_item = random.randint(1,1500)
            record = str(transaction_id)+','+str(transaction_sale_amount)+','+customer_name+','+str(category_of_item)
            if i < number_of_records-1:
                record += '\n'
            file.write(record)

        file.close()

